name: Configuration Assistant
id: ConfigAssistant
key: ConfigAssistant
author_link: https://github.com/openmelody/mt-plugin-configassistant
author_name: "Byrne Reese, Open Melody Software Group"
description: This plugin provides a simple YAML based framework for creating plugin and theme configuration options.
version: 2.5.19
static_version: 21
schema_version: 4

object_types:
  blog:
    selected_config: string meta

upgrade_functions:
  static_copy:
    # A version_limit is required to trigger the upgrade function. So, just
    # use a way big one, just so I don't have to remember to update it.
    version_limit: 999
    handler: $ConfigAssistant::ConfigAssistant::Static::upgrade

init_app: $ConfigAssistant::ConfigAssistant::Init::init_app

callbacks:
  MT::App::CMS::template_param.cfg_plugin:  $ConfigAssistant::ConfigAssistant::Plugin::xfrm_cfg_plugin_param
  MT::App::CMS::template_source.cfg_plugin: $ConfigAssistant::ConfigAssistant::Plugin::xfrm_cfg_plugin
  blog_template_set_change:                 $ConfigAssistant::ConfigAssistant::Prefs::on_template_set_change
  # For the asset Config Type
  template_param.asset_insert:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::Asset::asset_insert_param
    priority: 1

config_settings:
  PluginStaticVersion:
    type: 'HASH'

applications:
  cms:
    menus: $ConfigAssistant::ConfigAssistant::Init::update_menus
    methods:
      theme_options:    $ConfigAssistant::ConfigAssistant::Plugin::theme_options
      ca_config_entry:  $ConfigAssistant::ConfigAssistant::Plugin::list_entry_mini
      ca_config_page:   $ConfigAssistant::ConfigAssistant::Plugin::list_entry_mini
      ca_select_entry:  $ConfigAssistant::ConfigAssistant::Plugin::select_entry
      ca_config_entry_or_page: $ConfigAssistant::ConfigAssistant::Plugin::list_entry_or_page
      ca_select_entry_or_page: $ConfigAssistant::ConfigAssistant::Plugin::select_entry_or_page
      ca_select_author: $ConfigAssistant::ConfigAssistant::ConfigTypes::select_author
      ca_save_config:   $ConfigAssistant::ConfigAssistant::Plugin::save_config
      run_static_copy:  $ConfigAssistant::ConfigAssistant::Static::manual_run
      ca_prefs_apply:   $ConfigAssistant::ConfigAssistant::Prefs::apply
      ca_prefs_chooser: $ConfigAssistant::ConfigAssistant::Prefs::chooser

config_types:
  asset:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::Asset::type_asset
  author:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_author
  blogs:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_blogs
  category:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_category
  checkbox:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_checkbox
  colorpicker:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_colorpicker
  datetime:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_datetime
  entry:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_entry
  entry_or_page:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_entry_or_page
  file:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_file
  folder:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_folder
  link-group:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_link_group
  page:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_page
  radio:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_radio
  radio-image:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_radio_image
  select:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_select
  tagged-entry:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_tagged_entry
  text-group:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_text_group
  text:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_text
  textarea:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_textarea
  # Deprecated
  category_list:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_category_list
  folder_list:
    handler: $ConfigAssistant::ConfigAssistant::ConfigTypes::type_folder_list

blog_preferences:
  __default__:
    label: 'Factory Default'
    description: 'These are the default factory settings for Melody.'
    order: 1
    preferences: default_prefs.yaml
